version: "3.9"

services:
   # ----------------------
   # Postgres
   # ----------------------
   postgres:
      image: postgres:alpine3.22
      container_name: techibbie-dev-postgres
      networks:
         - dev-techibbie-net
      ports:
         - "5432:5432"
      environment:
         POSTGRES_USER: ${POSTGRES_USER}
         POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
         POSTGRES_DB: ${POSTGRES_DB}
      volumes:
         - pgdata:/var/lib/postgresql/data

   # ----------------------
   # MongoDB
   # ----------------------
   mongo:
      image: mongo:latest
      container_name: techibbie-dev-mongo
      networks:
         - dev-techibbie-net
      ports:
         - "27017:27017"
      environment:
         MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
         MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
         MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      volumes:
         - mongodata:/data/db

   # ----------------------
   # LocalStack (S3)
   # ----------------------
   localstack:
      image: localstack/localstack:latest
      container_name: techibbie-dev-localstack
      networks:
         - dev-techibbie-net
      ports:
         - "4566:4566"
         - "4510-4559:4510-4559"
      environment:
         SERVICES: ${LOCALSTACK_SERVICES}
         DEBUG: 1
         AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
         AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
         AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}

   # ----------------------
   # Auth - .Net API
   # ----------------------
   techibbie-auth-api:
      container_name: techibbie-dev-auth-api
      build:
         context: ../../
         dockerfile: services/auth/auth.api/Dockerfile.dev
      networks:
         - dev-techibbie-net
      ports:
         - "5000:8080"
         - "5001:8081"
      environment:
         DOTNET_ENV: Development
         ASPNETCORE_ENVIRONMENT: Development
      depends_on:
         - postgres
         - mongo
         - localstack

   # ----------------------
   # Auth - Next.js Frontend
   # ----------------------
   techibbie-auth-frontend:
      container_name: techibbie-dev-auth-frontend
      build:
         context: ../../services/auth/frontend
         dockerfile: docker/dockerfile.dev
      networks:
         - dev-techibbie-net
      ports:
         - "3000:3000"
      environment:
         NEXT_PUBLIC_API_URL: http://auth-api:5000
      depends_on:
         - techibbie-auth-api # assuming your .NET API service is named auth-api

networks:
   dev-techibbie-net:
      driver: bridge

volumes:
   pgdata:
   mongodata:
