# Dockerfile.dev
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 8080
EXPOSE 8081

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["services/auth/auth.api/auth.api.csproj", "services/auth/auth.api/"]
RUN dotnet restore "./services/auth/auth.api/auth.api.csproj"
COPY . .
WORKDIR "/src/services/auth/auth.api"
RUN dotnet build -c Debug -o /app/build

FROM build AS publish
RUN dotnet publish -c Debug -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
# Make sure container runs in Development
ENV DOTNET_ENV=Development
ENV ASPNETCORE_ENVIRONMENT=Development
ENTRYPOINT ["dotnet", "auth.api.dll"]