version: "3.9"

services:
   # ----------------------
   # Postgres
   # ----------------------
   postgres:
      image: postgres:alpine3.22
      container_name: techibbie-prod-postgres
      networks:
         - techibbie-net
      ports:
         - "5432:5432"
      environment:
         POSTGRES_USER: ${POSTGRES_USER}
         POSTGRES_DB: ${POSTGRES_DB}
         POSTGRES_PASSWORD_FILE: /run/secrets/pg_password
      secrets:
         - pg_password
      volumes:
         - pgdata:/var/lib/postgresql/data

   # ----------------------
   # MongoDB
   # ----------------------
   mongo:
      image: mongo:latest
      container_name: techibbie-prod-mongo
      networks:
         - techibbie-net
      ports:
         - "27017:27017"
      environment:
         MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
         MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
         MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/mongo_password
      secrets:
         - mongo_password
      volumes:
         - mongodata:/data/db
   # ----------------------
   # Auth - .Net API
   # ----------------------
   auth-api:
      build:
         context: ../../services/auth/api
         dockerfile: docker/dockerfile.prod
      container_name: techibbie-prod-auth-api
      networks:
         - techibbie-net
      ports:
         - "5000:5000"
      environment:
         DOTNET_ENV: Production
      depends_on:
         - postgres
         - mongo

   # ----------------------
   # Auth - Next.js Frontend
   # ----------------------
   frontend:
      build:
         context: ../../services/auth/frontend
         dockerfile: docker/dockerfile.prod
      container_name: techibbie-prod-frontend
      networks:
         - techibbie-net
      ports:
         - "3000:3000"
      environment:
         NEXT_PUBLIC_API_URL: http://auth-api:5000
      depends_on:
         - auth-api

# ----------------------
# Volumes
# ----------------------
volumes:
   pgdata:
   mongodata:

# ----------------------
# Networks
# ----------------------
networks:
   techibbie-net:
      driver: bridge

# ----------------------
# Secrets
# ----------------------
secrets:
   pg_password:
      external: true
   mongo_password:
      external: true
